In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
#import matplotlib.pyplot as plt
#import tensorflow as tf
from tensorflow import keras

In [54]:
data = np.loadtxt("wine.csv", delimiter=",", skiprows=1)
inputs = data[:, :11]
targets = data[:, 11]
min_t = min(targets)
max_t = max(targets)
# scale targets to 0-1 range
#targets = (targets - min_t) / (max_t - min_t)

inputs_train = inputs[:4500]
targets_train = targets[:4500]
inputs_test = inputs[4500:]
targets_test = targets[4500:]

input_size = 11
output_size = 1

In [55]:
# Build a neural network
# Setup some hyperparameters
WIDTH = 50
LEARNING_RATE = 0.00001
# Create a sequential model
model = Sequential()
# Add input layer
model.add(Dense(WIDTH, activation="elu", input_dim=input_size, kernel_initializer="uniform"))
# Add hidden layer
model.add(Dense(WIDTH, activation="relu", kernel_initializer="uniform"))
model.add(Dense(WIDTH, activation="selu", kernel_initializer="uniform"))
model.add(Dense(WIDTH, activation="selu", kernel_initializer="uniform"))
model.add(Dense(WIDTH, activation="selu", kernel_initializer="uniform"))
# Add output layer
model.add(Dense(1, activation="linear", kernel_initializer="uniform"))

# Compile model
model.compile(loss='mse', optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE))
model.fit(inputs_train, targets_train, epochs=1000, verbose=2)

Epoch 1/1000
141/141 - 0s - loss: 35.1832 - 454ms/epoch - 3ms/step
Epoch 2/1000
141/141 - 0s - loss: 34.7863 - 77ms/epoch - 548us/step
Epoch 3/1000
141/141 - 0s - loss: 33.5890 - 76ms/epoch - 536us/step
Epoch 4/1000
141/141 - 0s - loss: 30.6087 - 77ms/epoch - 549us/step
Epoch 5/1000
141/141 - 0s - loss: 25.4796 - 109ms/epoch - 771us/step
Epoch 6/1000
141/141 - 0s - loss: 19.2859 - 73ms/epoch - 517us/step
Epoch 7/1000
141/141 - 0s - loss: 13.3211 - 75ms/epoch - 531us/step
Epoch 8/1000
141/141 - 0s - loss: 8.3526 - 74ms/epoch - 528us/step
Epoch 9/1000
141/141 - 0s - loss: 4.7810 - 70ms/epoch - 499us/step
Epoch 10/1000
141/141 - 0s - loss: 2.6690 - 70ms/epoch - 500us/step
Epoch 11/1000
141/141 - 0s - loss: 1.7200 - 71ms/epoch - 507us/step
Epoch 12/1000
141/141 - 0s - loss: 1.4234 - 71ms/epoch - 503us/step
Epoch 13/1000
141/141 - 0s - loss: 1.3546 - 74ms/epoch - 525us/step
Epoch 14/1000
141/141 - 0s - loss: 1.3355 - 74ms/epoch - 524us/step
Epoch 15/1000
141/141 - 0s - loss: 1.3235 - 74ms/e

In [56]:
output_predict = model.predict_on_batch(inputs_test).round(0)
# rescale
#output_predict = output_predict * (max_t - min_t) + min_t
print(np.reshape(output_predict[:20], (20,)))

[6. 6. 6. 7. 6. 6. 6. 6. 6. 5. 7. 7. 7. 6. 5. 6. 6. 6. 5. 7.]


In [57]:
targets_round = targets_test.round(3)
# rescale
#targets_round = targets_round * (max_t - min_t) + min_t
print(targets_round[:20])

[6. 6. 6. 7. 5. 5. 6. 5. 4. 5. 6. 6. 6. 6. 5. 6. 6. 6. 6. 6.]


In [58]:
errors = np.abs(output_predict - targets_round)
print(errors)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [59]:
print('Euclidean distance:', np.linalg.norm(output_predict - targets_round))

Euclidean distance: 391.56353252058597
