# Simple linear regression with multiple features and multiple outputs

In [7]:
import numpy as np

In [8]:
N_OBSERVATIONS = 200
N_FEATURES = 5
N_OUTPUS = 2

# Generate random data for inputs & outputs
X = np.random.randn(N_OBSERVATIONS, N_FEATURES)
print(X[:4, :])
print('X shape = ', X.shape)
W0 = np.array([[1, 2.5], [2., 0.4], [10., -6.], [-7., 4.], [3.0, 0.]])
b0 = np.array([4.5, -3.5])
print('W shape = ', W0.shape)
print('b shape = ', b0.shape)

targets = np.dot(X, W0) + b0
print('Target shape = ', targets.shape)
# Generate random outputs
Y = np.dot(X, W0) + b0 + np.random.uniform(-1, 1, size=(N_OBSERVATIONS, N_OUTPUS))
print('Y shape = ', Y.shape)

[[ 0.81085013  1.65990317 -0.69234685 -1.16663094 -1.97535614]
 [-1.43099953  0.20949484 -0.55380229  0.28532619 -0.73233353]
 [ 0.13188025 -2.1255861   1.01701509 -1.14572007 -0.89678116]
 [-0.50882966  0.00709968  0.75296069 -0.13249528  0.4259629 ]]
X shape =  (200, 5)
W shape =  (5, 2)
b shape =  (2,)
Target shape =  (200, 2)
Y shape =  (200, 2)


In [9]:
# Initialize weights and biases
W = np.random.randn(N_FEATURES, N_OUTPUS)
b = np.random.randn(N_OUTPUS)
# Train model
LEARNING_RATE = 0.05
EPOCHS = 200
for epoch in range(EPOCHS):
    # Forward pass
    Y_pred = np.dot(X, W) + b
    error = Y_pred - Y
    # Compute loss
    loss = np.sum(error ** 2) / N_OBSERVATIONS
    # Backward pass
    grad_Y_pred = 2.0 * (Y_pred - Y)
    grad_W = np.dot(X.T, grad_Y_pred)
    grad_b = grad_Y_pred.sum(axis=0)
    # Update weights and biases
    W -= LEARNING_RATE * 2.0 * np.dot(X.T, error) / N_OBSERVATIONS
    b -= LEARNING_RATE * 2.0 * np.sum(error) / N_OBSERVATIONS

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: loss = {loss}")

Epoch 0: loss = 258.78747164732516
Epoch 10: loss = 61.784657417052095
Epoch 20: loss = 39.03015774840027
Epoch 30: loss = 36.05355474373889
Epoch 40: loss = 35.61766027732264
Epoch 50: loss = 35.54688394061347
Epoch 60: loss = 35.53439559873554
Epoch 70: loss = 35.53205579130054
Epoch 80: loss = 35.53159934738641
Epoch 90: loss = 35.531507932694105
Epoch 100: loss = 35.53148930916981
Epoch 110: loss = 35.53148547207495
Epoch 120: loss = 35.531484675439394
Epoch 130: loss = 35.5314845091625
Epoch 140: loss = 35.531484474323406
Epoch 150: loss = 35.53148446700315
Epoch 160: loss = 35.53148446546181
Epoch 170: loss = 35.531484465136735
Epoch 180: loss = 35.5314844650681
Epoch 190: loss = 35.53148446505358


In [10]:
print(f"Final loss = {loss}")
print(f"Final W = {W}")
print(f"Final b = {b}")


Final loss = 35.53148446505065
Final W = [[ 0.43217744  3.01606426]
 [ 2.38478164  0.09054692]
 [10.58447248 -6.59701429]
 [-7.38414595  4.37182019]
 [ 2.92116715  0.08498462]]
Final b = [0.19596017 0.78727064]


In [11]:
X_test = X[:10, :]
Y_test = np.dot(X_test, W) + b
print(Y_test)
print(targets[:10, :])


[[ 2.09994158e-02  2.68239230e+00]
 [-1.00307500e+01  1.32885253e+00]
 [ 1.17889820e+01 -1.08017932e+01]
 [ 1.01853517e+01 -6.25708718e+00]
 [-4.12444812e+00 -2.41245063e+00]
 [-9.04707301e+00  1.66017662e+00]
 [-1.09156895e+01  4.30451488e+00]
 [ 2.66717957e+01 -1.54533587e+01]
 [-1.48100544e+00  2.94012056e+00]
 [-8.44323830e+00  7.10316211e+00]]
[[  3.94753615  -1.32135609]
 [ -6.24431664  -2.5295824 ]
 [ 15.88055603 -14.70550467]
 [ 13.74033231  -9.81697958]
 [  0.05467308  -6.51036357]
 [ -4.32566793  -2.97162068]
 [ -6.43838597  -0.18616684]
 [ 29.3225358  -18.13157344]
 [  2.94824614  -1.4873842 ]
 [ -3.37727566   2.08770403]]
