# Simple linear regression with multiple features and multiple outputs

In [1]:
import numpy as np

In [27]:
N_OBSERVATIONS = 200
N_FEATURES = 5
N_OUTPUS = 2

# Generate random data for inputs & outputs
X = np.random.randn(N_OBSERVATIONS, N_FEATURES)
print(X[:4, :])
print(X.shape)
W0 = np.array([[1, 2.5], [2., 0.4], [10., -6.], [-7., 4.], [3.0, 0.]])
b0 = np.array([4.5, -3.5])
targets = np.dot(X, W0) + b0
print(targets.shape)
# Generate random outputs
Y = np.dot(X, W0) + b0 + np.random.uniform(-1, 1, size=(N_OBSERVATIONS, N_OUTPUS))
print(Y.shape)

[[-1.15768072 -1.50179749  0.83520243  0.43595171 -0.77312769]
 [ 1.03754635  1.17805982 -0.48613852 -1.02297863  0.61931774]
 [ 0.14692381  1.55202653  0.94323449  1.4407562   0.10691991]
 [ 1.06127887  0.34097152 -0.039931   -1.69613678  0.21541875]]
(200, 5)
(200, 2)
(200, 2)


In [32]:
# Initialize weights and biases
W = np.random.randn(N_FEATURES, N_OUTPUS)
b = np.random.randn(N_OUTPUS)
# Train model
LEARNING_RATE = 0.05
EPOCHS = 200
for epoch in range(EPOCHS):
    # Forward pass
    Y_pred = np.dot(X, W) + b
    error = Y_pred - Y
    # Compute loss
    loss = np.sum(error ** 2) / N_OBSERVATIONS
    # Backward pass
    grad_Y_pred = 2.0 * (Y_pred - Y)
    grad_W = np.dot(X.T, grad_Y_pred)
    grad_b = grad_Y_pred.sum(axis=0)
    # Update weights and biases
    W -= LEARNING_RATE * 2.0 * np.dot(X.T, error) / N_OBSERVATIONS
    b -= LEARNING_RATE * 2.0 * np.sum(error) / N_OBSERVATIONS

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: loss = {loss}")

Epoch 0: loss = 239.29920525430163
Epoch 10: loss = 57.64153701593188
Epoch 20: loss = 36.91878186734672
Epoch 30: loss = 34.51246211699868
Epoch 40: loss = 34.22595825089113
Epoch 50: loss = 34.19063536825392
Epoch 60: loss = 34.186073286470815
Epoch 70: loss = 34.185449252030764
Epoch 80: loss = 34.18535823328587
Epoch 90: loss = 34.18534408116408
Epoch 100: loss = 34.18534175235257
Epoch 110: loss = 34.185341351372706
Epoch 120: loss = 34.18534127999212
Epoch 130: loss = 34.18534126698858
Epoch 140: loss = 34.18534126458297
Epoch 150: loss = 34.185341264133456
Epoch 160: loss = 34.1853412640489
Epoch 170: loss = 34.18534126403293
Epoch 180: loss = 34.185341264029915
Epoch 190: loss = 34.18534126402934


In [33]:
print(f"Final loss = {loss}")
print(f"Final W = {W}")
print(f"Final b = {b}")


Final loss = 34.18534126402923
Final W = [[ 0.52910352  2.9833288 ]
 [ 2.15200822  0.28041952]
 [ 9.93170188 -5.90605525]
 [-6.55725812  3.51558812]
 [ 2.83454047  0.05481221]]
Final b = [0.3845536  0.64950746]
